# Copyright 2024 Vertikal Forening
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from odoo import models, fields, api, _
from odoo.exceptions import ValidationError, UserError
import datetime
import base64
import io
import xlsxwriter


class VfEconomyReport(models.Model):
    _name = 'vf.economy.report'
    _description = 'Economy Report'
    _order = 'date_generated desc'
    _rec_name = 'display_name'
    _inherit = ['mail.thread', 'mail.activity.mixin']

    # Core fields
    name = fields.Char(
        string='Report Name',
        required=True,
        tracking=True
    )
    report_type = fields.Selection([
        ('revenue', 'Revenue Report'),
        ('payment_status', 'Member Payment Status'),
        ('budget_actual', 'Budget vs Actual'),
        ('age_analysis', 'Age Analysis'),
        ('custom', 'Custom Report'),
    ], string='Report Type', required=True, tracking=True)
    
    # Period
    date_from = fields.Date(
        string='From Date',
        required=True,
        tracking=True
    )
    date_to = fields.Date(
        string='To Date',
        required=True,
        tracking=True
    )
    
    # Generation details
    date_generated = fields.Datetime(
        string='Generated On',
        required=True,
        default=fields.Datetime.now,
        readonly=True
    )
    generated_by = fields.Many2one(
        'res.users',
        string='Generated By',
        required=True,
        default=lambda self: self.env.user,
        readonly=True
    )
    
    # Filters
    section_ids = fields.Many2many(
        'vf.section',
        'vf_economy_report_section_rel',
        'report_id',
        'section_id',
        string='Sections'
    )
    group_ids = fields.Many2many(
        'vf.group',
        'vf_economy_report_group_rel',
        'report_id',
        'group_id',
        string='Groups'
    )
    fee_category_ids = fields.Many2many(
        'vf.fee.category',
        'vf_economy_report_fee_category_rel',
        'report_id',
        'category_id',
        string='Fee Categories'
    )
    
    # Report data
    report_data = fields.Text(
        string='Report Data (JSON)',
        readonly=True
    )
    attachment_id = fields.Many2one(
        'ir.attachment',
        string='Generated File',
        readonly=True
    )
    
    # Status
    state = fields.Selection([
        ('draft', 'Draft'),
        ('generated', 'Generated'),
        ('exported', 'Exported'),
        ('archived', 'Archived'),
    ], string='State', default='draft', required=True, tracking=True)
    
    # Computed fields
    display_name = fields.Char(
        compute='_compute_display_name',
        store=True
    )
    
    _sql_constraints = [
        ('date_check', 'CHECK(date_from <= date_to)', 
         'From date must be before or equal to to date!'),
    ]

    @api.depends('name', 'report_type', 'date_from', 'date_to')
    def _compute_display_name(self):
        for report in self:
            if report.name:
                report.display_name = report.name
            else:
                report.display_name = f'{dict(report._fields["report_type"].selection).get(report.report_type)} ' \
                                    f'{report.date_from} - {report.date_to}'

    def action_generate(self):
        """Generate the report based on type"""
        self.ensure_one()
        
        if self.report_type == 'revenue':
            data = self._generate_revenue_report()
        elif self.report_type == 'payment_status':
            data = self._generate_payment_status_report()
        elif self.report_type == 'budget_actual':
            data = self._generate_budget_actual_report()
        elif self.report_type == 'age_analysis':
            data = self._generate_age_analysis_report()
        else:
            data = self._generate_custom_report()
        
        self.report_data = str(data)
        self.state = 'generated'
        
        # Generate Excel file
        attachment = self._generate_excel_file(data)
        self.attachment_id = attachment.id
        
        return {
            'type': 'ir.actions.act_window',
            'name': 'Generated Report',
            'res_model': 'ir.attachment',
            'res_id': attachment.id,
            'view_mode': 'form',
            'target': 'new',
        }

    def _generate_revenue_report(self):
        """Generate revenue report data"""
        # Get fees within period
        domain = [
            ('generate_date', '>=', self.date_from),
            ('generate_date', '<=', self.date_to),
            ('state', 'in', ['pending', 'paid', 'overdue'])
        ]
        
        if self.section_ids:
            domain.append(('member_id.group_membership_ids.group_id.section_id', 'in', self.section_ids.ids))
        if self.group_ids:
            domain.append(('member_id.group_membership_ids.group_id', 'in', self.group_ids.ids))
        if self.fee_category_ids:
            domain.append(('category_id', 'in', self.fee_category_ids.ids))
        
        fees = self.env['vf.fee'].search(domain)
        
        # Group by category
        data = {
            'period': f'{self.date_from} - {self.date_to}',
            'categories': {},
            'total_revenue': 0,
            'total_paid': 0,
            'total_outstanding': 0,
        }
        
        for fee in fees:
            category = fee.category_id.name
            if category not in data['categories']:
                data['categories'][category] = {
                    'total': 0,
                    'paid': 0,
                    'outstanding': 0,
                    'count': 0,
                }
            
            data['categories'][category]['total'] += fee.amount
            data['categories'][category]['count'] += 1
            
            if fee.state == 'paid':
                data['categories'][category]['paid'] += fee.paid_amount
                data['total_paid'] += fee.paid_amount
            else:
                data['categories'][category]['outstanding'] += fee.remaining_amount
                data['total_outstanding'] += fee.remaining_amount
            
            data['total_revenue'] += fee.amount
        
        return data

    def _generate_payment_status_report(self):
        """Generate member payment status report"""
        # Get all active members
        members = self.env['vf.member'].search([('status', '=', 'active')])
        
        data = {
            'period': f'{self.date_from} - {self.date_to}',
            'members': [],
            'summary': {
                'total_members': len(members),
                'fully_paid': 0,
                'partially_paid': 0,
                'not_paid': 0,
                'overdue': 0,
            }
        }
        
        for member in members:
            # Get fees for the period
            fees = self.env['vf.fee'].search([
                ('member_id', '=', member.id),
                ('generate_date', '>=', self.date_from),
                ('generate_date', '<=', self.date_to),
            ])
            
            total_amount = sum(fees.mapped('amount'))
            total_paid = sum(fees.mapped('paid_amount'))
            remaining = sum(fees.mapped('remaining_amount'))
            
            status = 'not_paid'
            if total_paid >= total_amount:
                status = 'fully_paid'
                data['summary']['fully_paid'] += 1
            elif total_paid > 0:
                status = 'partially_paid'
                data['summary']['partially_paid'] += 1
            else:
                data['summary']['not_paid'] += 1
            
            # Check if overdue
            if any(f.state == 'overdue' for f in fees):
                status = 'overdue'
                data['summary']['overdue'] += 1
            
            member_data = {
                'membership_number': member.membership_number,
                'name': member.partner_id.name,
                'email': member.partner_id.email,
                'phone': member.partner_id.phone,
                'total_amount': total_amount,
                'total_paid': total_paid,
                'remaining': remaining,
                'status': status,
            }
            data['members'].append(member_data)
        
        return data

    def _generate_budget_actual_report(self):
        """Generate budget vs actual report"""
        # This is a placeholder - in a real implementation, 
        # you would have budget records to compare against
        data = {
            'period': f'{self.date_from} - {self.date_to}',
            'message': 'Budget comparison requires budget module integration',
            'actual_revenue': 0,
            'budgeted_revenue': 0,
            'variance': 0,
        }
        
        # Get actual revenue from fees
        fees = self.env['vf.fee'].search([
            ('generate_date', '>=', self.date_from),
            ('generate_date', '<=', self.date_to),
            ('state', '!=', 'cancelled')
        ])
        
        data['actual_revenue'] = sum(fees.mapped('amount'))
        data['budgeted_revenue'] = data['actual_revenue'] * 1.1  # Example budget
        data['variance'] = data['budgeted_revenue'] - data['actual_revenue']
        
        return data

    def _generate_age_analysis_report(self):
        """Generate age analysis of outstanding fees"""
        today = fields.Date.today()
        
        # Get outstanding fees
        fees = self.env['vf.fee'].search([
            ('state', 'in', ['pending', 'overdue']),
            ('remaining_amount', '>', 0)
        ])
        
        data = {
            'as_of_date': today,
            'aging_buckets': {
                'current': {'count': 0, 'amount': 0},      # 0-30 days
                '30_60': {'count': 0, 'amount': 0},       # 31-60 days
                '60_90': {'count': 0, 'amount': 0},       # 61-90 days
                '90_plus': {'count': 0, 'amount': 0},     # 90+ days
            },
            'total_outstanding': 0,
        }
        
        for fee in fees:
            days_overdue = (today - fee.due_date).days
            amount = fee.remaining_amount
            
            if days_overdue <= 30:
                bucket = 'current'
            elif days_overdue <= 60:
                bucket = '30_60'
            elif days_overdue <= 90:
                bucket = '60_90'
            else:
                bucket = '90_plus'
            
            data['aging_buckets'][bucket]['count'] += 1
            data['aging_buckets'][bucket]['amount'] += amount
            data['total_outstanding'] += amount
        
        return data

    def _generate_custom_report(self):
        """Generate custom report based on selected parameters"""
        return {
            'message': 'Custom report template',
            'filters': {
                'sections': self.section_ids.mapped('name'),
                'groups': self.group_ids.mapped('name'),
                'fee_categories': self.fee_category_ids.mapped('name'),
            }
        }

    def _generate_excel_file(self, data):
        """Generate Excel file from report data"""
        output = io.BytesIO()
        workbook = xlsxwriter.Workbook(output)
        
        # Create worksheet
        worksheet = workbook.add_worksheet('Report')
        
        # Formats
        header_format = workbook.add_format({
            'bold': True,
            'bg_color': '#4F81BD',
            'font_color': 'white',
            'border': 1,
        })
        
        # Write header
        worksheet.write(0, 0, 'Economy Report', header_format)
        worksheet.write(1, 0, f'Report Type: {dict(self._fields["report_type"].selection).get(self.report_type)}')
        worksheet.write(2, 0, f'Period: {self.date_from} - {self.date_to}')
        worksheet.write(3, 0, f'Generated: {self.date_generated}')
        
        # Write data based on report type
        row = 5
        if self.report_type == 'revenue':
            worksheet.write(row, 0, 'Category', header_format)
            worksheet.write(row, 1, 'Total', header_format)
            worksheet.write(row, 2, 'Paid', header_format)
            worksheet.write(row, 3, 'Outstanding', header_format)
            worksheet.write(row, 4, 'Count', header_format)
            
            row += 1
            for category, values in data.get('categories', {}).items():
                worksheet.write(row, 0, category)
                worksheet.write(row, 1, values['total'])
                worksheet.write(row, 2, values['paid'])
                worksheet.write(row, 3, values['outstanding'])
                worksheet.write(row, 4, values['count'])
                row += 1
            
            # Totals
            worksheet.write(row, 0, 'TOTAL', header_format)
            worksheet.write(row, 1, data['total_revenue'])
            worksheet.write(row, 2, data['total_paid'])
            worksheet.write(row, 3, data['total_outstanding'])
        
        elif self.report_type == 'payment_status':
            worksheet.write(row, 0, 'Membership No', header_format)
            worksheet.write(row, 1, 'Name', header_format)
            worksheet.write(row, 2, 'Email', header_format)
            worksheet.write(row, 3, 'Total Amount', header_format)
            worksheet.write(row, 4, 'Paid', header_format)
            worksheet.write(row, 5, 'Remaining', header_format)
            worksheet.write(row, 6, 'Status', header_format)
            
            row += 1
            for member in data.get('members', []):
                worksheet.write(row, 0, member['membership_number'])
                worksheet.write(row, 1, member['name'])
                worksheet.write(row, 2, member['email'])
                worksheet.write(row, 3, member['total_amount'])
                worksheet.write(row, 4, member['total_paid'])
                worksheet.write(row, 5, member['remaining'])
                worksheet.write(row, 6, member['status'])
                row += 1
        
        workbook.close()
        output.seek(0)
        
        # Create attachment
        filename = f'{self.name or "report"}_{fields.Date.today().strftime("%Y%m%d")}.xlsx'
        attachment = self.env['ir.attachment'].create({
            'name': filename,
            'type': 'binary',
            'datas': base64.b64encode(output.getvalue()),
            'res_model': self._name,
            'res_id': self.id,
        })
        
        return attachment

    def action_export(self):
        """Export the report"""
        self.ensure_one()
        
        if not self.attachment_id:
            raise UserError(_('Please generate the report first.'))
        
        self.state = 'exported'
        
        return {
            'type': 'ir.actions.act_url',
            'url': f'/web/content/{self.attachment_id.id}?download=true',
            'target': 'self',
        }

    def action_archive(self):
        """Archive the report"""
        self.write({'state': 'archived'})
        return True
