# Copyright 2024 Vertikal Forening
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

from odoo import models, fields, api, _
from odoo.exceptions import ValidationError, UserError
import datetime
import base64
import io
import xlsxwriter


class VfEconomyReport(models.Model):
    _name = 'vf.economy.report'
    _description = 'Economy Report'
    _order = 'date_generated desc'
    _rec_name = 'display_name'
    _inherit = ['mail.thread', 'mail.activity.mixin']

    # Core fields
    name = fields.Char(
        string='Report Name',
        required=True,
        tracking=True
    )
    report_type = fields.Selection([
        ('revenue', 'Revenue Report'),
        ('payment_status', 'Member Payment Status'),
        ('budget_actual', 'Budget vs Actual'),
        ('age_analysis', 'Age Analysis'),
        ('custom', 'Custom Report'),
    ], string='Report Type', required=True, tracking=True)
    
    # Period
    date_from = fields.Date(
        string='From Date',
        required=True,
        tracking=True
    )
    date_to = fields.Date(
        string='To Date',
        required=True,
        tracking=True
    )
    
    # Generation details
    date_generated = fields.Datetime(
        string='Generated On',
        required=True,
        default=fields.Datetime.now,
        readonly=True
    )
    generated_by = fields.Many2one(
        'res.users',
        string='Generated By',
        default=lambda self: self.env.user,
        readonly=True
    )
    
    # Filters
    group_ids = fields.Many2many(
        'vf.group',
        'vf_report_group_rel',
        'report_id',
        'group_id',
        string='Groups'
    )
    section_ids = fields.Many2many(
        'vf.section',
        'vf_report_section_rel',
        'report_id',
        'section_id',
        string='Sections'
    )
    member_ids = fields.Many2many(
        'vf.member',
        'vf_report_member_rel',
        'report_id',
        'member_id',
        string='Members'
    )
    
    # Status
    state = fields.Selection([
        ('draft', 'Draft'),
        ('generated', 'Generated'),
        ('error', 'Error'),
    ], string='Status', default='draft', required=True, tracking=True)
    
    # Results
    report_data = fields.Text(
        string='Report Data',
        readonly=True,
        help='JSON data for the report'
    )
    attachment_id = fields.Many2one(
        'ir.attachment',
        string='Generated File',
        readonly=True
    )
    
    # Computed fields
    display_name = fields.Char(
        compute='_compute_display_name',
        store=True
    )
    
    _sql_constraints = [
        ('dates_check', 'CHECK(date_from <= date_to)', 
         'From date must be before or equal to to date!'),
    ]

    @api.depends('name', 'date_from', 'date_to')
    def _compute_display_name(self):
        for report in self:
            report.display_name = f'{report.name} ({report.date_from} - {report.date_to})'

    @api.constrains('date_from', 'date_to')
    def _check_dates(self):
        for report in self:
            if report.date_from > report.date_to:
                raise ValidationError(_('From date must be before to date.'))

    def action_generate(self):
        """Generate the report"""
        self.ensure_one()
        
        try:
            if self.report_type == 'revenue':
                self._generate_revenue_report()
            elif self.report_type == 'payment_status':
                self._generate_payment_status_report()
            elif self.report_type == 'budget_actual':
                self._generate_budget_actual_report()
            elif self.report_type == 'age_analysis':
                self._generate_age_analysis_report()
            elif self.report_type == 'custom':
                self._generate_custom_report()
            
            self.write({'state': 'generated'})
            return True
            
        except Exception as e:
            self.write({
                'state': 'error',
                'report_data': str(e)
            })
            raise UserError(_('Error generating report: %s') % str(e))

    def _generate_revenue_report(self):
        """Generate revenue report"""
        # Get fees in period
        domain = [
            ('date_due', '>=', self.date_from),
            ('date_due', '<=', self.date_to),
            ('state', '!=', 'cancelled')
        ]
        
        if self.group_ids:
            domain.append(('member_id.group_ids', 'in', self.group_ids.ids))
        if self.section_ids:
            domain.append(('member_id.group_ids.section_id', 'in', self.section_ids.ids))
        if self.member_ids:
            domain.append(('member_id', 'in', self.member_ids.ids))
        
        fees = self.env['vf.fee'].search(domain)
        
        # Generate Excel
        workbook = xlsxwriter.Workbook(io.BytesIO())
        worksheet = workbook.add_worksheet('Revenue Report')
        
        # Headers
        headers = ['Date', 'Member', 'Fee Type', 'Amount', 'Paid', 'Outstanding', 'Status']
        for col, header in enumerate(headers):
            worksheet.write(0, col, header)
        
        # Data
        row = 1
        for fee in fees:
            worksheet.write(row, 0, fee.date_due or '')
            worksheet.write(row, 1, fee.member_id.name or '')
            worksheet.write(row, 2, fee.fee_type_id.name or '')
            worksheet.write(row, 3, fee.amount or 0)
            worksheet.write(row, 4, fee.paid_amount or 0)
            worksheet.write(row, 5, fee.remaining_amount or 0)
            worksheet.write(row, 6, fee.state or '')
            row += 1
        
        # Save
        output = io.BytesIO()
        workbook.close()
        output.seek(0)
        
        # Create attachment
        attachment = self.env['ir.attachment'].create({
            'name': f'{self.name}.xlsx',
            'datas': base64.b64encode(output.read()),
            'res_model': self._name,
            'res_id': self.id,
        })
        
        self.attachment_id = attachment.id

    def _generate_payment_status_report(self):
        """Generate payment status report"""
        # Similar implementation for payment status
        pass

    def _generate_budget_actual_report(self):
        """Generate budget vs actual report"""
        # Similar implementation for budget vs actual
        pass

    def _generate_age_analysis_report(self):
        """Generate age analysis report"""
        # Similar implementation for age analysis
        pass

    def _generate_custom_report(self):
        """Generate custom report"""
        # Similar implementation for custom report
        pass

    def action_download(self):
        """Download the report"""
        self.ensure_one()
        if not self.attachment_id:
            raise UserError(_('No report file available.'))
        
        return {
            'type': 'ir.actions.act_url',
            'url': f'/web/content/{self.attachment_id.id}?download=true',
            'target': 'self',
        }

    def action_email(self):
        """Email the report"""
        self.ensure_one()
        if not self.attachment_id:
            raise UserError(_('No report file available.'))
        
        return {
            'name': _('Email Report'),
            'type': 'ir.actions.act_window',
            'res_model': 'mail.compose.message',
            'view_mode': 'form',
            'target': 'new',
            'context': {
                'default_composition_mode': 'mass_mail',
                'default_notify': True,
                'default_attachment_ids': [(6, 0, [self.attachment_id.id])],
            },
        }
